on:
  workflow_run:
    workflows: [Build]
    types: [completed]
  
jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Run all tests
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage"

      - name: Report and publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          xunit_files: "**/TestResults/TestResults.xml"
          comment_mode: off
